name: Develop Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Defcon NULL.sln                      # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

     #Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
            
    - name: Build Server
      run: dotnet publish .\Server\Server.csproj -c Release --runtime linux-x64
    
    - name: Build MasterServer
      run: dotnet publish .\MasterServer\MasterServer.csproj -c Release --runtime linux-x64

        
     # You may pin to the exact commit or the version.
    # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
    - name: Upload Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 109.255.215.173
        username: ftpuser
        password: ${{ secrets.FTPPASS }}
        protocol: ftps
        local-dir: ./Server/bin/Release/net8.0/linux-x64/publish/
        server-dir: etetgame/develop/
        timeout: 100000
        security: loose
        dangerous-clean-slate: true

    - name: Upload Master Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 109.255.215.173
        username: ftpuser
        password: ${{ secrets.FTPPASS }}
        protocol: ftps
        local-dir: ./MasterServer/bin/Release/net8.0/linux-x64/publish/
        server-dir: etetgame/develop/
        timeout: 100000
        security: loose
        dangerous-clean-slate: true

    - name: Reboot Develop Master Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 109.255.215.173
        username: suha
        password: ${{ secrets.sudopass }}
        script: sudo systemctl restart etetgameServerDevelop.service; ${{ secrets.sudopass }}
        

   
